before_install:
  - git clone https://github.com/crayfishx/jerakia
  - ln -s jerakia/jerakia-puppet .


script:
  - cd jerakia
  - bundle exec rake integration_tests

language: ruby
rvm:
#  - 1.9.3
#  - 2.0
#  - 2.1
  - 2.2

env:
 global:
   - BUNDLE_GEMFILE=jerakia/Gemfile
 matrix:
#    - PUPPET_GEM_VERSION="~> 3.6.2"
#    - PUPPET_GEM_VERSION="~> 3.7.0"
#    - PUPPET_GEM_VERSION="~> 3.8.0"
#    - PUPPET_GEM_VERSION="~> 3.8.6"
#    - PUPPET_GEM_VERSION="~> 4.1.0"
#    - PUPPET_GEM_VERSION="~> 4.2.0"
#    - PUPPET_GEM_VERSION="~> 4.3.0"
#    - PUPPET_GEM_VERSION="~> 4.4.0"
    - PUPPET_GEM_VERSION="~> 4.5.0"

matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.6.2"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.8.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.8.6"
